# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 03:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import django_prices.models
import geoposition.fields
import image_cropping.fields
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.CITIES_CITY_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('number', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('cropping', image_cropping.fields.ImageRatioField('image', '1200x960', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', django_fsm.FSMField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=50, protected=True)),
                ('description', models.CharField(max_length=255)),
            ],
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', django_fsm.FSMField(choices=[('recruitment_on', 'Recruitment available'), ('suspended', 'Suspended'), ('resumed', 'Resumed'), ('recruitment_off', 'Recruitment complete')], default='recruitment_on', max_length=50, protected=True)),
                ('price', django_prices.models.PriceField(currency='USD', decimal_places=2, max_digits=4, verbose_name='Price')),
                ('meeting', geoposition.fields.GeopositionField(max_length=42)),
                ('destination', geoposition.fields.GeopositionField(max_length=42)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveler.Car')),
                ('route_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_from', to=settings.CITIES_CITY_MODEL)),
                ('route_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_to', to=settings.CITIES_CITY_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', django_fsm.FSMField(choices=[('in_progress', 'In progress'), ('complete', 'Complete')], default='in_progress', max_length=50, protected=True)),
                ('current_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.CITIES_CITY_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveler.Route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
        migrations.AddField(
            model_name='proposal',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveler.Route'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='photoes',
            field=models.ManyToManyField(to='traveler.Image'),
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='travel',
            unique_together=set([('user', 'route')]),
        ),
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together=set([('user', 'route')]),
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together=set([('user', 'number')]),
        ),
    ]
